//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public int Id { get; set; }
        public string ImageURL { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public int UploadBy { get; set; }
        public int Status { get; set; }
        public string Details { get; set; }
        public Nullable<int> LinkId { get; set; }
        public bool IsActive { get; set; }
        public string MobileImageURL { get; set; }
    }
}
