//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LakbayDBEntities : DbContext
    {
        public LakbayDBEntities()
            : base("name=LakbayDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Baranggay> Baranggays { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CMSUser> CMSUsers { get; set; }
        public virtual DbSet<CMSUserRole> CMSUserRoles { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<FirebaseUserToken> FirebaseUserTokens { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<PlaceFacility> PlaceFacilities { get; set; }
        public virtual DbSet<PlaceImage> PlaceImages { get; set; }
        public virtual DbSet<PlaceReview> PlaceReviews { get; set; }
        public virtual DbSet<Province> Provinces { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserLinkedAccount> UserLinkedAccounts { get; set; }
        public virtual DbSet<UserPlaceVisitHistory> UserPlaceVisitHistories { get; set; }
        public virtual DbSet<UserUploadedFile> UserUploadedFiles { get; set; }
        public virtual DbSet<PlaceOperatingHour> PlaceOperatingHours { get; set; }
    }
}
