//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceReview
    {
        public int Id { get; set; }
        public int PlaceId { get; set; }
        public string Username { get; set; }
        public int ReviewStars { get; set; }
        public string ReviewText { get; set; }
        public System.DateTime CreatedDatte { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual User User { get; set; }
    }
}
