//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Place()
        {
            this.Cities = new HashSet<City>();
            this.Favorites = new HashSet<Favorite>();
            this.PlaceImages = new HashSet<PlaceImage>();
            this.UserPlaceVisitHistories = new HashSet<UserPlaceVisitHistory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> BaranggayId { get; set; }
        public string CompleteAddress { get; set; }
        public string Title { get; set; }
        public string ContactNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string DescriptionHTML { get; set; }
        public string Directions { get; set; }
        public string Url { get; set; }
        public int PaymentOption { get; set; }
        public int Type { get; set; }
        public bool IsDeleted { get; set; }
        public string HomeThumbnail { get; set; }
        public string HomeSlug { get; set; }
        public Nullable<decimal> DistanceFromManila { get; set; }
        public Nullable<int> TotalPlaces { get; set; }
        public Nullable<int> DisplayPriority { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string PublishedBy { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string TagLine { get; set; }
        public string MapsLongtitude { get; set; }
        public string MapsLatitude { get; set; }
        public string HeaderVideoURL { get; set; }
        public string GUID { get; set; }
        public string ShopURL { get; set; }
    
        public virtual Baranggay Baranggay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorite> Favorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaceImage> PlaceImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPlaceVisitHistory> UserPlaceVisitHistories { get; set; }
    }
}
