//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceOperatingHour
    {
        public int Id { get; set; }
        public int PlaceId { get; set; }
        public int Day { get; set; }
        public System.TimeSpan TimeFrom { get; set; }
        public System.TimeSpan TimeTo { get; set; }
    }
}
