//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaceImage
    {
        public int Id { get; set; }
        public int PlaceId { get; set; }
        public string Filename { get; set; }
        public int Type { get; set; }
        public string ImageText { get; set; }
        public string YoutubeUrl { get; set; }
    
        public virtual Place Place { get; set; }
    }
}
