//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_queue
    {
        public int id { get; set; }
        public string sender { get; set; }
        public string recipient { get; set; }
        public string message { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public int status { get; set; }
    }
}
