//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserUploadedFile
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Path { get; set; }
        public int Type { get; set; }
        public string Filename { get; set; }
        public string FileExtension { get; set; }
        public string FileSize { get; set; }
        public int UploadBy { get; set; }
        public System.DateTime DateUploaded { get; set; }
        public System.DateTime LastDateModified { get; set; }
        public string Remarks { get; set; }
        public bool IsDeleted { get; set; }
        public string Guid { get; set; }
    }
}
