//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Database.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLinkedAccount
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string LinkId { get; set; }
        public int Type { get; set; }
        public System.DateTime DateLinked { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsVerified { get; set; }
    
        public virtual User User { get; set; }
    }
}
